ath25: switch default kernel to 5.15
Switch to kernel 5.15 although it is marked as source only. It is marked
as source only because nobody was able to test this device.

Merging this is important to finally branch a new release. We want to
get rid completely of 5.10 kernel. Without this commit we get following
error: "Missing kernel version/hash file for 5.10." Hopfully someone
will fix the board in the rc phase or it will be removed completly.

Signed-off-by: Nick Hainke <vincent@systemli.org>