ath79: 5.15: drop unused res variable from pci ar724x OF convert patch
Drop unused res variable from pci ar724x OF convert patch fixing
compilation warning:

arch/mips/pci/pci-ar724x.c: In function 'ar724x_pci_probe':
arch/mips/pci/pci-ar724x.c:387:26: error: unused variable 'res' [-Werror=unused-variable]
  387 |         struct resource *res;
      |                          ^~~
cc1: all warnings being treated as errors

Signed-off-by: Christian Marangi <ansuelsmth@gmail.com>